import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { AuthProvider } from './context/AuthContext'
import NavBarWithAuth from './components/NavBarWithAuth/NavBarWithAuth'

export const metadata: Metadata = {
  title: 'Cardápio Serviços UFCAT - Admin',
  description: 'Generated by create next app',
}

const rawline = localFont({ src: '/fonts/rawline-500.ttf' })
// const workSans = localFont({ src: '/fonts/WorkSans-Regular.ttf' })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${rawline.className} bg-gray-ufcat`}>
        <AuthProvider>
          <NavBarWithAuth>
            <main className="flex flex-1 justify-center">{children}</main>
          </NavBarWithAuth>
        </AuthProvider>
      </body>
    </html>
  )
}
