import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { AuthProvider } from './context/AuthContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const rawline = localFont({ src: '/fonts/rawline-500.ttf' })
// const workSans = localFont({ src: '/fonts/WorkSans-Regular.ttf' })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${rawline.className} bg-gray-ufcat`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
